using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Imaging;
using System.Media;
using System.Resources;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;

namespace clodagh_dyeing
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new Container();
            ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(MainForm));
            this.radioButton1 = new RadioButton();
            this.radioButton2 = new RadioButton();
            this.radioButton3 = new RadioButton();
            this.label_goal3 = new Label();
            this.desired1_r2 = new TextBox();
            this.MultiBtn = new Button();
            this.label_goal2 = new Label();
            this.desired1_g2 = new TextBox();
            this.whitechecker = new CheckBox();
            this.label_color3b = new Label();
            this.label1 = new Label();
            this.label_goal1 = new Label();
            this.label3 = new Label();
            this.desired1_r = new TextBox();
            this.graycheck = new CheckBox();
            this.blackcheck = new CheckBox();
            this.desired1_g = new TextBox();
            this.desired1_b = new TextBox();
            this.desired1_b2 = new TextBox();
            this.desired2_r = new TextBox();
            this.desired2_b = new TextBox();
            this.label39 = new Label();
            this.desired2_g = new TextBox();
            this.label38 = new Label();
            this.label_totalgold = new Label();
            this.desired2_r2 = new TextBox();
            this.label_color1g = new Label();
            this.label_color1r = new Label();
            this.label_color1b = new Label();
            this.label_color3g = new Label();
            this.label_color2g = new Label();
            this.label_color2b = new Label();
            this.label_color2r = new Label();
            this.groupBox3 = new GroupBox();
            this.label40 = new Label();
            this.desired2_g2 = new TextBox();
            this.label25 = new Label();
            this.desired2_b2 = new TextBox();
            this.label26 = new Label();
            this.desired3_r = new TextBox();
            this.label27 = new Label();
            this.desired3_g = new TextBox();
            this.desired3_b = new TextBox();
            this.desired3_r2 = new TextBox();
            this.label5 = new Label();
            this.desired3_g2 = new TextBox();
            this.label4 = new Label();
            this.desired3_b2 = new TextBox();
            this.groupBox2 = new GroupBox();
            this.colorP1 = new Panel();
            this.ShowColorBtn = new Button();
            this.colorP2 = new Panel();
            this.colorP3 = new Panel();
            this.label_color3r = new Label();
            this.offcheck = new CheckBox();
            this.groupBox1 = new GroupBox();
            this.label_totalcount = new Label();
            this.dyecount = new Label();
            this.payed = new Label();
            this.toolTip1 = new ToolTip(this.components);
            this.textBox1 = new TextBox();
            this.waittimectrl = new NumericUpDown();
            this.clo_dialog = new Label();
            this.label_count = new Label();
            this.timeoutBox = new TextBox();
            this.backgroundWorker1 = new BackgroundWorker();
            this.groupBox4 = new GroupBox();
            this.label_cost = new Label();
            this.label6 = new Label();
            this.label2 = new Label();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((ISupportInitialize)this.waittimectrl).BeginInit();
            this.groupBox4.SuspendLayout();
            base.SuspendLayout();
            this.radioButton1.AutoSize = true;
            this.radioButton1.Checked = true;
            this.radioButton1.FlatStyle = FlatStyle.Flat;
            this.radioButton1.Font = new Font("Microsoft Sans Serif", 9f);
            this.radioButton1.ForeColor = Color.Black;
            this.radioButton1.Location = new Point(44, 21);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.RightToLeft = RightToLeft.Yes;
            this.radioButton1.Size = new Size(58, 19);
            this.radioButton1.TabIndex = 2016;
            this.radioButton1.TabStop = true;
            this.radioButton1.Text = "파트 1";
            this.radioButton1.UseVisualStyleBackColor = true;
            this.radioButton2.AutoSize = true;
            this.radioButton2.FlatStyle = FlatStyle.Flat;
            this.radioButton2.Font = new Font("Microsoft Sans Serif", 9f);
            this.radioButton2.ForeColor = Color.Black;
            this.radioButton2.Location = new Point(108, 21);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.RightToLeft = RightToLeft.Yes;
            this.radioButton2.Size = new Size(58, 19);
            this.radioButton2.TabIndex = 2017;
            this.radioButton2.Text = "파트 2";
            this.radioButton2.UseVisualStyleBackColor = true;
            this.radioButton3.AutoSize = true;
            this.radioButton3.FlatStyle = FlatStyle.Flat;
            this.radioButton3.Font = new Font("Microsoft Sans Serif", 9f);
            this.radioButton3.ForeColor = Color.Black;
            this.radioButton3.Location = new Point(171, 21);
            this.radioButton3.Name = "radioButton3";
            this.radioButton3.RightToLeft = RightToLeft.Yes;
            this.radioButton3.Size = new Size(58, 19);
            this.radioButton3.TabIndex = 2018;
            this.radioButton3.Text = "파트 3";
            this.radioButton3.UseVisualStyleBackColor = true;
            this.label_goal3.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_goal3.ForeColor = Color.Black;
            this.label_goal3.Location = new Point(204, 50);
            this.label_goal3.Name = "label_goal3";
            this.label_goal3.Size = new Size(88, 16);
            this.label_goal3.TabIndex = 2015;
            this.label_goal3.Text = "목표 색상";
            this.label_goal3.TextAlign = ContentAlignment.MiddleCenter;
            this.desired1_r2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired1_r2.ForeColor = Color.Black;
            this.desired1_r2.Location = new Point(68, 68);
            this.desired1_r2.MaxLength = 3;
            this.desired1_r2.Name = "desired1_r2";
            this.desired1_r2.Size = new Size(28, 21);
            this.desired1_r2.TabIndex = 6;
            this.desired1_r2.Text = "0";
            this.toolTip1.SetToolTip(this.desired1_r2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.MultiBtn.FlatAppearance.BorderColor = Color.Black;
            this.MultiBtn.FlatAppearance.MouseDownBackColor = Color.DarkGray;
            this.MultiBtn.FlatAppearance.MouseOverBackColor = Color.DarkGray;
            this.MultiBtn.FlatStyle = FlatStyle.System;
            this.MultiBtn.Font = new Font("Microsoft Sans Serif", 9f);
            this.MultiBtn.ForeColor = Color.Black;
            this.MultiBtn.Location = new Point(9, 307);
            this.MultiBtn.Name = "MultiBtn";
            this.MultiBtn.Size = new Size(116, 25);
            this.MultiBtn.TabIndex = 2038;
            this.MultiBtn.TabStop = false;
            this.MultiBtn.Text = "다중 색상 확인";
            this.toolTip1.SetToolTip(this.MultiBtn, "모든 파트를 동시에 체크하여\n모두 지정 범위에 있으면 염색을 멈춥니다.");
            this.MultiBtn.UseVisualStyleBackColor = true;
            this.MultiBtn.Click += new EventHandler(this.MultiBtn_Click);
            this.label_goal2.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_goal2.ForeColor = Color.Black;
            this.label_goal2.Location = new Point(111, 50);
            this.label_goal2.Name = "label_goal2";
            this.label_goal2.Size = new Size(98, 16);
            this.label_goal2.TabIndex = 2014;
            this.label_goal2.Text = "목표 색상";
            this.label_goal2.TextAlign = ContentAlignment.MiddleCenter;
            this.desired1_g2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired1_g2.ForeColor = Color.Black;
            this.desired1_g2.Location = new Point(68, 92);
            this.desired1_g2.MaxLength = 3;
            this.desired1_g2.Name = "desired1_g2";
            this.desired1_g2.Size = new Size(28, 21);
            this.desired1_g2.TabIndex = 7;
            this.desired1_g2.Text = "0";
            this.toolTip1.SetToolTip(this.desired1_g2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.whitechecker.FlatStyle = FlatStyle.Flat;
            this.whitechecker.Font = new Font("Microsoft Sans Serif", 9f);
            this.whitechecker.ForeColor = Color.Black;
            this.whitechecker.Location = new Point(107, 142);
            this.whitechecker.Name = "whitechecker";
            this.whitechecker.Size = new Size(82, 24);
            this.whitechecker.TabIndex = 80;
            this.whitechecker.Text = "255 STOP";
            this.toolTip1.SetToolTip(this.whitechecker, "체크하면 현재 확인중인 파트가 아니더라도\nRGB(255,255,255)가 뜨면 멈춥니다.");
            this.label_color3b.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color3b.ForeColor = Color.Black;
            this.label_color3b.Location = new Point(113, 84);
            this.label_color3b.Name = "label_color3b";
            this.label_color3b.Size = new Size(28, 14);
            this.label_color3b.TabIndex = 2021;
            this.label_color3b.Text = "000";
            this.label_color3b.TextAlign = ContentAlignment.TopCenter;
            this.label1.BackColor = SystemColors.ActiveCaption;
            this.label1.BorderStyle = BorderStyle.FixedSingle;
            this.label1.Font = new Font("Microsoft Sans Serif", 9f);
            this.label1.ForeColor = Color.Black;
            this.label1.Location = new Point(14, 17);
            this.label1.Name = "label1";
            this.label1.Size = new Size(268, 33);
            this.label1.TabIndex = 2034;
            this.label1.Text = "다중 색상확인은 \n동시에 모든 파트의 색을 확인하는 모드입니다.";
            this.label1.TextAlign = ContentAlignment.MiddleCenter;
            this.label1.Visible = false;
            this.label_goal1.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_goal1.ForeColor = Color.Black;
            this.label_goal1.Location = new Point(26, 50);
            this.label_goal1.Name = "label_goal1";
            this.label_goal1.Size = new Size(87, 16);
            this.label_goal1.TabIndex = 2;
            this.label_goal1.Text = "목표 색상";
            this.label_goal1.TextAlign = ContentAlignment.MiddleCenter;
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Microsoft Sans Serif", 9f);
            this.label3.ForeColor = Color.Black;
            this.label3.Location = new Point(14, 71);
            this.label3.Name = "label3";
            this.label3.Size = new Size(16, 15);
            this.label3.TabIndex = 4;
            this.label3.Text = "R";
            this.desired1_r.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired1_r.ForeColor = Color.Black;
            this.desired1_r.Location = new Point(38, 68);
            this.desired1_r.MaxLength = 3;
            this.desired1_r.Name = "desired1_r";
            this.desired1_r.Size = new Size(28, 21);
            this.desired1_r.TabIndex = 3;
            this.desired1_r.Text = "0";
            this.toolTip1.SetToolTip(this.desired1_r, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.graycheck.FlatStyle = FlatStyle.Flat;
            this.graycheck.Font = new Font("Microsoft Sans Serif", 9f);
            this.graycheck.ForeColor = Color.Black;
            this.graycheck.Location = new Point(17, 142);
            this.graycheck.Name = "graycheck";
            this.graycheck.Size = new Size(79, 24);
            this.graycheck.TabIndex = 2002;
            this.graycheck.Text = "230 STOP";
            this.toolTip1.SetToolTip(this.graycheck, "체크하면 현재 확인중인 파트가 아니더라도\nRGB(230,230,230)가 뜨면 멈춥니다.");
            this.blackcheck.FlatStyle = FlatStyle.Flat;
            this.blackcheck.Font = new Font("Microsoft Sans Serif", 9f);
            this.blackcheck.ForeColor = Color.Black;
            this.blackcheck.Location = new Point(197, 142);
            this.blackcheck.Name = "blackcheck";
            this.blackcheck.Size = new Size(81, 24);
            this.blackcheck.TabIndex = 2001;
            this.blackcheck.Text = "  25 STOP";
            this.toolTip1.SetToolTip(this.blackcheck, "체크하면 현재 확인중인 파트가 아니더라도\nRGB(25,25,25)가 뜨면 멈춥니다.");
            this.desired1_g.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired1_g.ForeColor = Color.Black;
            this.desired1_g.Location = new Point(38, 92);
            this.desired1_g.MaxLength = 3;
            this.desired1_g.Name = "desired1_g";
            this.desired1_g.Size = new Size(28, 21);
            this.desired1_g.TabIndex = 4;
            this.desired1_g.Text = "0";
            this.toolTip1.SetToolTip(this.desired1_g, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.desired1_b.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired1_b.ForeColor = Color.Black;
            this.desired1_b.Location = new Point(38, 116);
            this.desired1_b.MaxLength = 3;
            this.desired1_b.Name = "desired1_b";
            this.desired1_b.Size = new Size(28, 21);
            this.desired1_b.TabIndex = 5;
            this.desired1_b.Text = "0";
            this.toolTip1.SetToolTip(this.desired1_b, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.desired1_b2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired1_b2.ForeColor = Color.Black;
            this.desired1_b2.Location = new Point(68, 116);
            this.desired1_b2.MaxLength = 3;
            this.desired1_b2.Name = "desired1_b2";
            this.desired1_b2.Size = new Size(28, 21);
            this.desired1_b2.TabIndex = 8;
            this.desired1_b2.Text = "0";
            this.toolTip1.SetToolTip(this.desired1_b2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.desired2_r.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired2_r.ForeColor = Color.Black;
            this.desired2_r.Location = new Point(130, 68);
            this.desired2_r.MaxLength = 3;
            this.desired2_r.Name = "desired2_r";
            this.desired2_r.Size = new Size(28, 21);
            this.desired2_r.TabIndex = 9;
            this.desired2_r.Text = "0";
            this.toolTip1.SetToolTip(this.desired2_r, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.desired2_b.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired2_b.ForeColor = Color.Black;
            this.desired2_b.Location = new Point(130, 116);
            this.desired2_b.MaxLength = 3;
            this.desired2_b.Name = "desired2_b";
            this.desired2_b.Size = new Size(28, 21);
            this.desired2_b.TabIndex = 11;
            this.desired2_b.Text = "0";
            this.toolTip1.SetToolTip(this.desired2_b, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label39.AutoSize = true;
            this.label39.Font = new Font("Microsoft Sans Serif", 9f);
            this.label39.ForeColor = Color.Black;
            this.label39.Location = new Point(195, 121);
            this.label39.Name = "label39";
            this.label39.Size = new Size(15, 15);
            this.label39.TabIndex = 59;
            this.label39.Text = "B";
            this.desired2_g.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired2_g.ForeColor = Color.Black;
            this.desired2_g.Location = new Point(130, 92);
            this.desired2_g.MaxLength = 3;
            this.desired2_g.Name = "desired2_g";
            this.desired2_g.Size = new Size(28, 21);
            this.desired2_g.TabIndex = 10;
            this.desired2_g.Text = "0";
            this.toolTip1.SetToolTip(this.desired2_g, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label38.AutoSize = true;
            this.label38.Font = new Font("Microsoft Sans Serif", 9f);
            this.label38.ForeColor = Color.Black;
            this.label38.Location = new Point(195, 96);
            this.label38.Name = "label38";
            this.label38.Size = new Size(16, 15);
            this.label38.TabIndex = 60;
            this.label38.Text = "G";
            this.label_totalgold.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_totalgold.ForeColor = Color.Black;
            this.label_totalgold.Location = new Point(14, 56);
            this.label_totalgold.Name = "label_totalgold";
            this.label_totalgold.Size = new Size(137, 16);
            this.label_totalgold.TabIndex = 78;
            this.label_totalgold.Text = "소모 비용";
            this.label_totalgold.TextAlign = ContentAlignment.MiddleCenter;
            this.desired2_r2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired2_r2.ForeColor = Color.Black;
            this.desired2_r2.Location = new Point(160, 68);
            this.desired2_r2.MaxLength = 3;
            this.desired2_r2.Name = "desired2_r2";
            this.desired2_r2.Size = new Size(28, 21);
            this.desired2_r2.TabIndex = 12;
            this.desired2_r2.Text = "0";
            this.toolTip1.SetToolTip(this.desired2_r2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label_color1g.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color1g.ForeColor = Color.Black;
            this.label_color1g.Location = new Point(17, 71);
            this.label_color1g.Name = "label_color1g";
            this.label_color1g.Size = new Size(28, 14);
            this.label_color1g.TabIndex = 2029;
            this.label_color1g.Text = "000";
            this.label_color1g.TextAlign = ContentAlignment.TopCenter;
            this.label_color1r.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color1r.ForeColor = Color.Black;
            this.label_color1r.Location = new Point(17, 58);
            this.label_color1r.Name = "label_color1r";
            this.label_color1r.Size = new Size(28, 14);
            this.label_color1r.TabIndex = 2028;
            this.label_color1r.Text = "000";
            this.label_color1r.TextAlign = ContentAlignment.TopCenter;
            this.label_color1b.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color1b.ForeColor = Color.Black;
            this.label_color1b.Location = new Point(17, 84);
            this.label_color1b.Name = "label_color1b";
            this.label_color1b.Size = new Size(28, 14);
            this.label_color1b.TabIndex = 2027;
            this.label_color1b.Text = "000";
            this.label_color1b.TextAlign = ContentAlignment.TopCenter;
            this.label_color3g.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color3g.ForeColor = Color.Black;
            this.label_color3g.Location = new Point(113, 71);
            this.label_color3g.Name = "label_color3g";
            this.label_color3g.Size = new Size(28, 14);
            this.label_color3g.TabIndex = 2023;
            this.label_color3g.Text = "000";
            this.label_color3g.TextAlign = ContentAlignment.TopCenter;
            this.label_color2g.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color2g.ForeColor = Color.Black;
            this.label_color2g.Location = new Point(65, 71);
            this.label_color2g.Name = "label_color2g";
            this.label_color2g.Size = new Size(28, 14);
            this.label_color2g.TabIndex = 2026;
            this.label_color2g.Text = "000";
            this.label_color2g.TextAlign = ContentAlignment.TopCenter;
            this.label_color2b.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color2b.ForeColor = Color.Black;
            this.label_color2b.Location = new Point(65, 84);
            this.label_color2b.Name = "label_color2b";
            this.label_color2b.Size = new Size(28, 14);
            this.label_color2b.TabIndex = 2024;
            this.label_color2b.Text = "000";
            this.label_color2b.TextAlign = ContentAlignment.TopCenter;
            this.label_color2r.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color2r.ForeColor = Color.Black;
            this.label_color2r.Location = new Point(65, 58);
            this.label_color2r.Name = "label_color2r";
            this.label_color2r.Size = new Size(28, 14);
            this.label_color2r.TabIndex = 2025;
            this.label_color2r.Text = "000";
            this.label_color2r.TextAlign = ContentAlignment.TopCenter;
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Controls.Add(this.radioButton1);
            this.groupBox3.Controls.Add(this.radioButton2);
            this.groupBox3.Controls.Add(this.radioButton3);
            this.groupBox3.Controls.Add(this.label_goal1);
            this.groupBox3.Controls.Add(this.label3);
            this.groupBox3.Controls.Add(this.desired1_r);
            this.groupBox3.Controls.Add(this.label_goal3);
            this.groupBox3.Controls.Add(this.graycheck);
            this.groupBox3.Controls.Add(this.blackcheck);
            this.groupBox3.Controls.Add(this.desired1_g);
            this.groupBox3.Controls.Add(this.label_goal2);
            this.groupBox3.Controls.Add(this.desired1_b);
            this.groupBox3.Controls.Add(this.desired1_r2);
            this.groupBox3.Controls.Add(this.desired1_g2);
            this.groupBox3.Controls.Add(this.whitechecker);
            this.groupBox3.Controls.Add(this.desired1_b2);
            this.groupBox3.Controls.Add(this.desired2_r);
            this.groupBox3.Controls.Add(this.desired2_g);
            this.groupBox3.Controls.Add(this.label38);
            this.groupBox3.Controls.Add(this.desired2_b);
            this.groupBox3.Controls.Add(this.label39);
            this.groupBox3.Controls.Add(this.desired2_r2);
            this.groupBox3.Controls.Add(this.label40);
            this.groupBox3.Controls.Add(this.desired2_g2);
            this.groupBox3.Controls.Add(this.label25);
            this.groupBox3.Controls.Add(this.desired2_b2);
            this.groupBox3.Controls.Add(this.label26);
            this.groupBox3.Controls.Add(this.desired3_r);
            this.groupBox3.Controls.Add(this.label27);
            this.groupBox3.Controls.Add(this.desired3_g);
            this.groupBox3.Controls.Add(this.desired3_b);
            this.groupBox3.Controls.Add(this.desired3_r2);
            this.groupBox3.Controls.Add(this.label5);
            this.groupBox3.Controls.Add(this.desired3_g2);
            this.groupBox3.Controls.Add(this.label4);
            this.groupBox3.Controls.Add(this.desired3_b2);
            this.groupBox3.Location = new Point(11, 129);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(298, 173);
            this.groupBox3.TabIndex = 2041;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Option";
            this.label40.AutoSize = true;
            this.label40.Font = new Font("Microsoft Sans Serif", 9f);
            this.label40.ForeColor = Color.Black;
            this.label40.Location = new Point(195, 71);
            this.label40.Name = "label40";
            this.label40.Size = new Size(16, 15);
            this.label40.TabIndex = 56;
            this.label40.Text = "R";
            this.desired2_g2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired2_g2.ForeColor = Color.Black;
            this.desired2_g2.Location = new Point(160, 92);
            this.desired2_g2.MaxLength = 3;
            this.desired2_g2.Name = "desired2_g2";
            this.desired2_g2.Size = new Size(28, 21);
            this.desired2_g2.TabIndex = 13;
            this.desired2_g2.Text = "0";
            this.toolTip1.SetToolTip(this.desired2_g2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label25.AutoSize = true;
            this.label25.Font = new Font("Microsoft Sans Serif", 9f);
            this.label25.ForeColor = Color.Black;
            this.label25.Location = new Point(106, 96);
            this.label25.Name = "label25";
            this.label25.Size = new Size(16, 15);
            this.label25.TabIndex = 38;
            this.label25.Text = "G";
            this.desired2_b2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired2_b2.ForeColor = Color.Black;
            this.desired2_b2.Location = new Point(160, 116);
            this.desired2_b2.MaxLength = 3;
            this.desired2_b2.Name = "desired2_b2";
            this.desired2_b2.Size = new Size(28, 21);
            this.desired2_b2.TabIndex = 49;
            this.desired2_b2.Text = "0";
            this.toolTip1.SetToolTip(this.desired2_b2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label26.AutoSize = true;
            this.label26.Font = new Font("Microsoft Sans Serif", 9f);
            this.label26.ForeColor = Color.Black;
            this.label26.Location = new Point(106, 121);
            this.label26.Name = "label26";
            this.label26.Size = new Size(15, 15);
            this.label26.TabIndex = 37;
            this.label26.Text = "B";
            this.desired3_r.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired3_r.ForeColor = Color.Black;
            this.desired3_r.Location = new Point(220, 68);
            this.desired3_r.MaxLength = 3;
            this.desired3_r.Name = "desired3_r";
            this.desired3_r.Size = new Size(28, 21);
            this.desired3_r.TabIndex = 55;
            this.desired3_r.Text = "0";
            this.toolTip1.SetToolTip(this.desired3_r, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label27.AutoSize = true;
            this.label27.Font = new Font("Microsoft Sans Serif", 9f);
            this.label27.ForeColor = Color.Black;
            this.label27.Location = new Point(106, 71);
            this.label27.Name = "label27";
            this.label27.Size = new Size(16, 15);
            this.label27.TabIndex = 34;
            this.label27.Text = "R";
            this.desired3_g.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired3_g.ForeColor = Color.Black;
            this.desired3_g.Location = new Point(220, 92);
            this.desired3_g.MaxLength = 3;
            this.desired3_g.Name = "desired3_g";
            this.desired3_g.Size = new Size(28, 21);
            this.desired3_g.TabIndex = 56;
            this.desired3_g.Text = "0";
            this.toolTip1.SetToolTip(this.desired3_g, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.desired3_b.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired3_b.ForeColor = Color.Black;
            this.desired3_b.Location = new Point(220, 116);
            this.desired3_b.MaxLength = 3;
            this.desired3_b.Name = "desired3_b";
            this.desired3_b.Size = new Size(28, 21);
            this.desired3_b.TabIndex = 57;
            this.desired3_b.Text = "0";
            this.toolTip1.SetToolTip(this.desired3_b, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.desired3_r2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired3_r2.ForeColor = Color.Black;
            this.desired3_r2.Location = new Point(251, 68);
            this.desired3_r2.MaxLength = 3;
            this.desired3_r2.Name = "desired3_r2";
            this.desired3_r2.Size = new Size(28, 21);
            this.desired3_r2.TabIndex = 70;
            this.desired3_r2.Text = "0";
            this.toolTip1.SetToolTip(this.desired3_r2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Microsoft Sans Serif", 9f);
            this.label5.ForeColor = Color.Black;
            this.label5.Location = new Point(14, 96);
            this.label5.Name = "label5";
            this.label5.Size = new Size(16, 15);
            this.label5.TabIndex = 8;
            this.label5.Text = "G";
            this.desired3_g2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired3_g2.ForeColor = Color.Black;
            this.desired3_g2.Location = new Point(251, 92);
            this.desired3_g2.MaxLength = 3;
            this.desired3_g2.Name = "desired3_g2";
            this.desired3_g2.Size = new Size(28, 21);
            this.desired3_g2.TabIndex = 72;
            this.desired3_g2.Text = "0";
            this.toolTip1.SetToolTip(this.desired3_g2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Microsoft Sans Serif", 9f);
            this.label4.ForeColor = Color.Black;
            this.label4.Location = new Point(14, 121);
            this.label4.Name = "label4";
            this.label4.Size = new Size(15, 15);
            this.label4.TabIndex = 7;
            this.label4.Text = "B";
            this.desired3_b2.Font = new Font("Microsoft Sans Serif", 9f);
            this.desired3_b2.ForeColor = Color.Black;
            this.desired3_b2.Location = new Point(251, 116);
            this.desired3_b2.MaxLength = 3;
            this.desired3_b2.Name = "desired3_b2";
            this.desired3_b2.Size = new Size(28, 21);
            this.desired3_b2.TabIndex = 74;
            this.desired3_b2.Text = "0";
            this.toolTip1.SetToolTip(this.desired3_b2, "원하는 RGB값의 범위를 입력합니다.\n단일확인모드에선 3개의 범위 중 하나만 만족하면 염색이 멈추며\n원하는 지정색이 없으면 RGB 모두 0 | 0로 입력하세요.");
            this.groupBox2.Controls.Add(this.colorP1);
            this.groupBox2.Controls.Add(this.ShowColorBtn);
            this.groupBox2.Controls.Add(this.colorP2);
            this.groupBox2.Controls.Add(this.label_color1g);
            this.groupBox2.Controls.Add(this.colorP3);
            this.groupBox2.Controls.Add(this.label_color3b);
            this.groupBox2.Controls.Add(this.label_color1r);
            this.groupBox2.Controls.Add(this.label_color3r);
            this.groupBox2.Controls.Add(this.label_color1b);
            this.groupBox2.Controls.Add(this.label_color3g);
            this.groupBox2.Controls.Add(this.label_color2g);
            this.groupBox2.Controls.Add(this.label_color2b);
            this.groupBox2.Controls.Add(this.label_color2r);
            this.groupBox2.Location = new Point(315, 155);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(160, 147);
            this.groupBox2.TabIndex = 2035;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Color";
            this.colorP1.BorderStyle = BorderStyle.FixedSingle;
            this.colorP1.Enabled = false;
            this.colorP1.Font = new Font("Microsoft Sans Serif", 9f);
            this.colorP1.ForeColor = Color.Black;
            this.colorP1.Location = new Point(17, 26);
            this.colorP1.Name = "colorP1";
            this.colorP1.Size = new Size(30, 30);
            this.colorP1.TabIndex = 30;
            this.ShowColorBtn.FlatAppearance.BorderColor = Color.Black;
            this.ShowColorBtn.FlatAppearance.MouseDownBackColor = Color.DarkGray;
            this.ShowColorBtn.FlatAppearance.MouseOverBackColor = Color.DarkGray;
            this.ShowColorBtn.FlatStyle = FlatStyle.System;
            this.ShowColorBtn.Font = new Font("Microsoft Sans Serif", 9f);
            this.ShowColorBtn.ForeColor = Color.Black;
            this.ShowColorBtn.Location = new Point(32, 108);
            this.ShowColorBtn.Name = "ShowColorBtn";
            this.ShowColorBtn.Size = new Size(97, 25);
            this.ShowColorBtn.TabIndex = 2000;
            this.ShowColorBtn.TabStop = false;
            this.ShowColorBtn.Text = "Show Color";
            this.ShowColorBtn.UseMnemonic = false;
            this.ShowColorBtn.UseVisualStyleBackColor = false;
            this.ShowColorBtn.Click += new EventHandler(this.ShowColorBtn_Click);
            this.colorP2.BorderStyle = BorderStyle.FixedSingle;
            this.colorP2.Enabled = false;
            this.colorP2.Font = new Font("Microsoft Sans Serif", 9f);
            this.colorP2.ForeColor = Color.Black;
            this.colorP2.Location = new Point(65, 26);
            this.colorP2.Name = "colorP2";
            this.colorP2.Size = new Size(30, 30);
            this.colorP2.TabIndex = 31;
            this.colorP3.BorderStyle = BorderStyle.FixedSingle;
            this.colorP3.Enabled = false;
            this.colorP3.Font = new Font("Microsoft Sans Serif", 9f);
            this.colorP3.ForeColor = Color.Black;
            this.colorP3.Location = new Point(113, 26);
            this.colorP3.Name = "colorP3";
            this.colorP3.Size = new Size(30, 30);
            this.colorP3.TabIndex = 31;
            this.label_color3r.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_color3r.ForeColor = Color.Black;
            this.label_color3r.Location = new Point(113, 58);
            this.label_color3r.Name = "label_color3r";
            this.label_color3r.Size = new Size(28, 14);
            this.label_color3r.TabIndex = 2022;
            this.label_color3r.Text = "000";
            this.label_color3r.TextAlign = ContentAlignment.TopCenter;
            this.offcheck.FlatStyle = FlatStyle.Flat;
            this.offcheck.Font = new Font("Microsoft Sans Serif", 9f);
            this.offcheck.ForeColor = Color.Black;
            this.offcheck.ImageAlign = ContentAlignment.MiddleRight;
            this.offcheck.Location = new Point(136, 309);
            this.offcheck.Name = "offcheck";
            this.offcheck.Size = new Size(117, 24);
            this.offcheck.TabIndex = 2039;
            this.offcheck.Text = "컴퓨터 예약 종료";
            this.offcheck.TextAlign = ContentAlignment.MiddleRight;
            this.toolTip1.SetToolTip(this.offcheck, "지정된 횟수만큼 염색을 하거나\n원하는 색을 찾으면\n컴퓨터를 종료합니다.");
            this.groupBox1.Controls.Add(this.label_totalcount);
            this.groupBox1.Controls.Add(this.dyecount);
            this.groupBox1.Controls.Add(this.payed);
            this.groupBox1.Controls.Add(this.label_totalgold);
            this.groupBox1.Location = new Point(315, 43);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(160, 106);
            this.groupBox1.TabIndex = 2040;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Cost";
            this.label_totalcount.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_totalcount.ForeColor = Color.Black;
            this.label_totalcount.Location = new Point(14, 14);
            this.label_totalcount.Name = "label_totalcount";
            this.label_totalcount.Size = new Size(135, 16);
            this.label_totalcount.TabIndex = 77;
            this.label_totalcount.Text = "시도 횟수";
            this.label_totalcount.TextAlign = ContentAlignment.MiddleCenter;
            this.dyecount.BackColor = SystemColors.ControlLight;
            this.dyecount.BorderStyle = BorderStyle.FixedSingle;
            this.dyecount.Font = new Font("Microsoft Sans Serif", 9f);
            this.dyecount.ForeColor = Color.Black;
            this.dyecount.Location = new Point(14, 33);
            this.dyecount.Name = "dyecount";
            this.dyecount.Size = new Size(137, 21);
            this.dyecount.TabIndex = 75;
            this.dyecount.Text = "0";
            this.dyecount.TextAlign = ContentAlignment.MiddleCenter;
            this.payed.BackColor = SystemColors.ControlLight;
            this.payed.BorderStyle = BorderStyle.FixedSingle;
            this.payed.Font = new Font("Microsoft Sans Serif", 9f);
            this.payed.ForeColor = Color.Black;
            this.payed.Location = new Point(14, 75);
            this.payed.Name = "payed";
            this.payed.Size = new Size(137, 21);
            this.payed.TabIndex = 76;
            this.payed.Text = "0";
            this.payed.TextAlign = ContentAlignment.MiddleCenter;
            this.toolTip1.AutomaticDelay = 100;
            this.toolTip1.AutoPopDelay = 10000;
            this.toolTip1.InitialDelay = 100;
            this.toolTip1.IsBalloon = true;
            this.toolTip1.ReshowDelay = 20;
            this.toolTip1.UseAnimation = false;
            this.toolTip1.UseFading = false;
            this.textBox1.Font = new Font("Microsoft Sans Serif", 9f);
            this.textBox1.ForeColor = Color.Black;
            this.textBox1.Location = new Point(163, 40);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(119, 21);
            this.textBox1.TabIndex = 99;
            this.textBox1.Text = "0";
            this.toolTip1.SetToolTip(this.textBox1, "한번 염색하는데 필요한 골드를 입력하세요.");
            this.waittimectrl.DecimalPlaces = 1;
            this.waittimectrl.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.waittimectrl.Increment = new decimal(new int[] { 5, 0, 0, 65536 });
            this.waittimectrl.Location = new Point(413, 310);
            this.waittimectrl.Maximum = new decimal(new int[] { 10, 0, 0, 0 });
            this.waittimectrl.Minimum = new decimal(new int[] { 5, 0, 0, 0 });
            this.waittimectrl.Name = "waittimectrl";
            this.waittimectrl.Size = new Size(62, 21);
            this.waittimectrl.TabIndex = 2044;
            this.waittimectrl.TextAlign = HorizontalAlignment.Center;
            this.toolTip1.SetToolTip(this.waittimectrl, "염색 버튼을 누르고염색값을 확인하기까지 걸리는 시간입니다.\n회선, 서버의 상황에 맞게 조절해주세요");
            this.waittimectrl.Value = new decimal(new int[] { 5, 0, 0, 0 });
            this.clo_dialog.BackColor = SystemColors.Control;
            this.clo_dialog.Font = new Font("Microsoft Sans Serif", 9f);
            this.clo_dialog.ForeColor = Color.Black;
            this.clo_dialog.Location = new Point(2, 4);
            this.clo_dialog.Name = "clo_dialog";
            this.clo_dialog.Size = new Size(473, 36);
            this.clo_dialog.TabIndex = 2036;
            this.clo_dialog.Text = "염색 시작, 중지 : Home";
            this.clo_dialog.TextAlign = ContentAlignment.MiddleCenter;
            this.label_count.AutoSize = true;
            this.label_count.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_count.ForeColor = Color.Black;
            this.label_count.Location = new Point(23, 22);
            this.label_count.Name = "label_count";
            this.label_count.Size = new Size(58, 15);
            this.label_count.TabIndex = 11;
            this.label_count.Text = "반복 횟수";
            this.label_count.TextAlign = ContentAlignment.MiddleCenter;
            this.timeoutBox.Font = new Font("Microsoft Sans Serif", 9f);
            this.timeoutBox.ForeColor = Color.Black;
            this.timeoutBox.Location = new Point(16, 40);
            this.timeoutBox.Name = "timeoutBox";
            this.timeoutBox.Size = new Size(124, 21);
            this.timeoutBox.TabIndex = 999;
            this.timeoutBox.Text = "3000";
            this.timeoutBox.TextChanged += new EventHandler(this.timeoutBox_TextChanged);
            this.backgroundWorker1.WorkerReportsProgress = true;
            this.backgroundWorker1.DoWork += new DoWorkEventHandler(this.backgroundWorker1_DoWork);
            this.backgroundWorker1.ProgressChanged += new ProgressChangedEventHandler(this.backgroundWorker1_ProgressChanged);
            this.groupBox4.Controls.Add(this.label_count);
            this.groupBox4.Controls.Add(this.timeoutBox);
            this.groupBox4.Controls.Add(this.textBox1);
            this.groupBox4.Controls.Add(this.label_cost);
            this.groupBox4.Location = new Point(12, 43);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(297, 80);
            this.groupBox4.TabIndex = 2042;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Count";
            this.label_cost.AutoSize = true;
            this.label_cost.Font = new Font("Microsoft Sans Serif", 9f);
            this.label_cost.ForeColor = Color.Black;
            this.label_cost.Location = new Point(166, 22);
            this.label_cost.Name = "label_cost";
            this.label_cost.Size = new Size(58, 15);
            this.label_cost.TabIndex = 74;
            this.label_cost.Text = "염색 비용";
            this.label_cost.TextAlign = ContentAlignment.MiddleCenter;
            this.label6.BackColor = SystemColors.Control;
            this.label6.Font = new Font("Microsoft Sans Serif", 9f);
            this.label6.ForeColor = Color.Black;
            this.label6.Location = new Point(345, 305);
            this.label6.Name = "label6";
            this.label6.Size = new Size(63, 30);
            this.label6.TabIndex = 2046;
            this.label6.Text = "대기시간";
            this.label6.TextAlign = ContentAlignment.MiddleCenter;
            this.label2.BorderStyle = BorderStyle.FixedSingle;
            this.label2.Location = new Point(315, 306);
            this.label2.Name = "label2";
            this.label2.Size = new Size(25, 25);
            this.label2.TabIndex = 2047;
            this.label2.TextAlign = ContentAlignment.MiddleCenter;
            this.label2.UseCompatibleTextRendering = true;
            this.label2.Click += new EventHandler(this.label2_Click);
            base.AutoScaleDimensions = new SizeF(7f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.AutoSize = true;
            base.ClientSize = new Size(481, 335);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.waittimectrl);
            base.Controls.Add(this.MultiBtn);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.offcheck);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.clo_dialog);
            base.Controls.Add(this.groupBox4);
            base.FormBorderStyle = FormBorderStyle.FixedSingle;
           //base.Icon = (Icon)componentResourceManager.GetObject("$this.Icon");
            base.MaximizeBox = false;
            base.Name = "MainForm";
            this.Text = "클로다 개년";
            base.TopMost = true;
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            ((ISupportInitialize)this.waittimectrl).EndInit();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            base.ResumeLayout(false);
        }

        #endregion
    }
}